<?php

use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/modelo1.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Envase PET 500 ml Generico 18.5 grs",
            'nombre'     => "Envase PET 500 ml Generico 18.5 grs",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-50",
            'model'  => "assets/models/mdl_bote_01.obj",
            'tX'     => "0",
            'tY'     => "-10",
            'tZ'     => "0",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "0",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_preforma_pet_33mm.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_preforma_pet_1816mm.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_preforma_pet_1881mm.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_carbonatada_csd_1_v1_28mm_1881.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_carbonatada_csd8_28mm_1881.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_liner_af6_pn_y_pr_1816_mm.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_liner_pc_1881_mm.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_nocarbonatada_33mm.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_nocarbonatada_CAF4_1816.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);

        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_nocarbonatada_caf5_28mm_1881.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_01.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_02.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_03_02.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_03.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_04_02.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_04.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapa_noname_05_parte_03.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapon_01.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        DB::table('productos')->insert([
            'descripcion'    => "Tapa",
            'nombre'     => "Tapa",
            'codigo'     => "000",
            'foto'   => null,
            'marcaDes'   => "",
            'estado'     => "1",
            'marcado'    => "",
            'hasModel'   => true,
            'fov'    => "50",
            'near'   => "1",
            'far'    => "1100",
            'pX'     => "-5",
            'pY'     => "0",
            'pZ'     => "-10",
            'model'  => "assets/models/mdl_tapon_02.obj",
            'tX'     => "0",
            'tY'     => "0",
            'tZ'     => "25",
            'rX'     => "0",
            'rY'     => "0",
            'rZ'     => "-25",
            'tipo'   => 1,
            'categoria'   => 1,
            'marca'   => 1,
            'deleted_at'       => null,
            'created_at'       => date('Y-m-d H:m:s'),
            'updated_at'       => date('Y-m-d H:m:s')
        ]);
        
    }
}
